import Editor from '@monaco-editor/react'
import mermaid from 'mermaid'
import Head from 'next/head'
import { useEffect, useRef, useState, MouseEvent } from 'react'
import { TransformWrapper, TransformComponent } from 'react-zoom-pan-pinch'

export default function Home() {
  const mermaidRef = useRef<HTMLDivElement>(null)
  const editorRef = useRef(null)
  const [panelStyles, setPanelStyles] = useState({ transform: 'translate(0px, 0px) scale(1)' })
  const [content, setContent] = useState('')
  const [mouseDown, setMouseDown] = useState(false)
  const [pageX, setPageX] = useState(0)
  const [pageY, setPageY] = useState(0)
  const [scale, setScale] = useState(1)

  const editorOptions = {
    minimap: { enabled: false },
    fontSize: 14,
  }

  mermaid.initialize({
    startOnLoad: true,
    securityLevel: 'strict',
    theme: 'neutral',
  })

  useEffect(() => {
    if (mermaidRef.current && content) {
      mermaid.contentLoaded()
      mermaidRef.current.removeAttribute('data-processed')
    }
  }, [content])

  function handleEditorChange(value) {
    setContent(value)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex h-screen flex-col overflow-y-hidden'>
        <div className='sticky top-0 z-10 w-full border-b px-2 py-1'>
          <div>Mermaid Live Editor</div>
        </div>
        <main className='grid flex-1 grid-cols-12'>
          <div className='col-span-4 border-r'>
            <div>
              <Editor
                height='100vh'
                options={editorOptions}
                onChange={handleEditorChange}
                onMount={(editor) => (editorRef.current = editor)}
              />
            </div>
          </div>
          <div className='col-span-8 h-full'>
            <TransformWrapper minScale={0.5} centerZoomedOut={true} centerOnInit={true}>
              <TransformComponent contentClass='bg-dotted tr-comp' wrapperClass='tr-wrapper'>
                <div className='flex h-full w-full items-center justify-center'>
                  <div ref={mermaidRef} className='mermaid'>
                    {content}
                  </div>
                </div>
              </TransformComponent>
            </TransformWrapper>
          </div>
        </main>
      </div>
    </>
  )
}
